//! # axiom
//!
//! **Func + Machine: typed ports, explicit topology, deploy-time physics.**
//!
//! Zero-dependency computation primitives for observable, controllable systems.
//! `Func` (stack, stateless) and `Machine` (heap, stateful) are organized around
//! seven core primitives — [`Func`], [`Port`], [`Flow`], [`Session`], [`Topology`],
//! [`Lifecycle`], [`Machine`] — with typed I/O, explicit link topology,
//! deployment specs, and resource classification.
//!
//! axiom is a **pure contract layer**: it defines typed ports, flow semantics,
//! session protocols, and deployment specs — the vocabulary a runtime adapter
//! interprets. The core crate carries no runtime, no executor, no async, and
//! (outside the optional `serialize` feature) no dependencies.
//!
//! ## Features
//!
//! | Feature | Default | What it enables |
//! |---------|---------|-----------------|
//! | `std` | yes | `std::error::Error` impls, `ConfigCell`/`MigrateRegistry` (RwLock-backed), `RealClock` wall-clock |
//! | `serialize` | no | `serde::Serialize`/`Deserialize` on pure-data enums & structs |
//!
//! Build with `--no-default-features` for a `no_std + alloc` configuration
//! (embedded/WASM): the pure-data + `alloc` subset compiles without std.
//! Collection types come from `crate::compat` so the crate stays
//! zero-dependency in both configurations.
//!
//! ## Module maturity (T2)
//!
//! The 31 public modules are grouped into three maturity tiers to help
//! users tell the "stable core" apart from "experimental extensions".
//! Each tier's meaning: **stable** = the stable core, the main subject of
//! the current refactor; **experimental** = extensions (advanced as part of
//! the core, not feature-gated, not dropped); **tool** = development-time
//! tooling / runtime-adapter constraints, hardened according to a unified
//! convention.
//!
//! | Tier | Modules |
//! |----|------|
//! | **stable** (stable core) | [`func`](crate::func) / [`machine`](crate::machine) / [`port`](crate::port) / [`portset`](crate::portset) / [`link`](crate::link) / [`deploy`](crate::deploy) / [`flow`](crate::flow) / [`resource`](crate::resource) / [`static_exec`](crate::static_exec) / [`topology`](crate::topology) / [`analysis`](crate::analysis) / [`compat`](crate::compat) / [`time`](crate::time) |
//! | **experimental** (extensions, advanced as core) | [`session`](crate::session) / [`hybrid`](crate::hybrid) / [`projection`](crate::projection) / [`stream`](crate::stream) / [`composite`](crate::composite) / [`entity`](crate::entity) / [`migrate`](crate::migrate) / [`shared`](crate::shared) / [`backpressure`](crate::backpressure) / [`builtin`](crate::builtin) |
//! | **tool** (tooling) | [`lint`](crate::lint) / [`runtime_contract`](crate::runtime_contract) / [`config`](crate::config) / [`blueprint`](crate::blueprint) |
//!
//! **Experimental extensions are not part of the default export surface.**
//! The `hybrid`, `stream`, and `shared` modules stay `pub mod` (reachable by
//! explicit path, `axiom::hybrid::…`) but are **deliberately excluded from
//! `prelude_all`**: a machine morphology that does not map 1:1 to a blueprint
//! decision adds neither blueprint truthfulness nor redemption verifiability
//! (design principle §0.5.1 in `docs/design-principles.md`), so it must be
//! opted into explicitly rather than appearing in the default vocabulary.
//!
//! [`Func`]: crate::func::Func
//! [`Port`]: crate::port
//! [`Flow`]: crate::flow
//! [`Session`]: crate::session
//! [`Topology`]: crate::topology
//! [`Lifecycle`]: crate::machine
//! [`Machine`]: crate::machine::Machine

// Enable `#[doc(cfg)]` rendering on docs.rs (nightly-only, gated so stable
// builds are unaffected).
#![cfg_attr(docsrs, feature(doc_cfg))]

// axiom core contains no `unsafe` — make that a compile-time promise (an
// ecosystem precedent). The runtime's lock-free ring (`CarFreeRing`) and replay entries
// live in `axiom-runtime`, outside this crate.
#![forbid(unsafe_code)]

// axiom supports a `no_std + alloc` build. With the default `std` feature the
// crate uses `std::collections`/`std::sync::RwLock`/`std::time`; without it,
// the pure-data + `alloc` subset compiles on embedded/WASM targets. The
// `std::error::Error` impls, the RwLock-backed `ConfigCell`/`MigrateRegistry`,
// and `RealClock` are gated behind `#[cfg(feature = "std")]`. Collection types
// come from `crate::compat` so they map to `BTreeMap`/`BTreeSet` under `no_std`.
#![cfg_attr(not(feature = "std"), no_std)]
extern crate alloc;

// Code generated by the procedural macro references core types via the
// absolute `::axiom::` path. Inside the axiom crate itself, `extern crate
// self` makes that path available. This is only needed when the `derive`
// feature is enabled (only then does macro-generated code exist).
#[cfg(feature = "derive")]
extern crate self as axiom;

// Procedural-macro entry point — when the `derive` feature is enabled,
// `#[axiom::ports]` becomes available. The procedural macro runs at compile
// time and the generated code references `::axiom::` paths, so it is
// compatible with no_std.
#[cfg(feature = "derive")]
pub use axiom_derive::ports;

// axiom core targets `std` by default. A `no_std` + `alloc` configuration is
// available for embedded/edge use — the error types below gate their
// `std::error::Error` impls behind `#[cfg(feature = "std")]`.

// ═══════════════════════════════════════════════════════════════════════════
// Module maturity tiers (T2, see "Module maturity" in the crate docs)
//   stable          — the stable core (main subject of the current refactor)
//   experimental    — extensions (advanced as part of the core, not dropped,
//                     marked experimental)
//   tool            — development-time tooling / runtime-adapter constraints
// ═══════════════════════════════════════════════════════════════════════════

// ── stable: the stable core ────────────────────────────────────────────────
// 新主轴线：四构件编译期核心（开放系统/因果数据流/组合/静态性声明）。
// 旧模块逐步迁移/删除（见 refactor-plan-compile-time-core.md）。
pub mod cell_core;
pub mod analysis;
pub mod compat;
pub mod deploy;
pub mod flow;
pub mod func;
pub mod link;
pub mod machine;
pub mod port;
pub mod portset;
pub mod resource;
pub mod static_exec;
pub mod time;
pub mod topology;

// ── experimental: extensions (advanced as core, not dropped) ───────────────
pub mod backpressure;
pub mod builtin;
pub mod composite;
pub mod entity;
pub mod hybrid;
pub mod migrate;
pub mod projection;
pub mod session;
pub mod shared;
pub mod stream;

// ── tool: development-time tooling / runtime-adapter constraints ───────────
pub mod lint;
pub mod runtime_contract;
#[cfg(feature = "serialize")]
pub mod blueprint;
#[cfg(feature = "std")]
pub mod config;

/// Core prelude for typical use.
pub mod prelude_all {
    pub use crate::cell_core::{
        Blueprint, Broadcast, CellChain, Feedback, Link, PortCell, Static,
        blueprint_is_zero_sized, drive,
    };
    pub use crate::backpressure::{
        BackpressurePolicy, BackpressureAction, BackpressureCtx,
        BlockPolicy, DropPolicy, OverwritePolicy, CreditPolicy,
    };
    pub use crate::builtin::{
        Identity, Sink, Tee, Latch, Collector, EntityRoot, FuncMachine,
    };
    pub use crate::composite::{CompositeSpec, CompositeError, expand_composites};
    pub use crate::deploy::{DynamicTopology, DeploySettings, MachineInstance, FuncBinding, Patch, ValidationError, CycleRule};
    #[cfg(feature = "std")]
    pub use crate::config::{ConfigCell, ConfigError};
    pub use crate::entity::{Entity, EntityRestoreError};
    pub use crate::flow::FlowKind;
    pub use crate::func::{Func, FuncRef, FuncWithScratch, FuncScratchPipeline, Scratched, CostEstimate};
    pub use crate::link::{LinkKind, LinkSpec, WritePolicy, ReadPolicy, MemoryRegion};
    pub use crate::machine::{
        Machine, Moore, ProcessOutput, InitError, CleanupError,
        MachineHandle, LifecycleState,
        Init, Running, Stopping, Stopped,
        SingleOutput, MultiOutput, TupleOutput, MachineOutput, FusedInline, FusedCompatible,
    };
    #[cfg(feature = "std")]
    pub use crate::migrate::{SchemaMigrate, MigrateFn, MigrateRegistry};
    pub use crate::port::{
        PortDir, PortDecl, PortSchema, ConfigDecl, ConfigSchema, MachineContext,
        LinkCompat, Lifecycle, SystemSignal,
    };
    pub use crate::portset::{
        PortSet, HasPortInfo,
        In, Out, SinglePorts,        // single-port convenience
        NoInput, NoOutput,           // empty-port convenience
    };
    pub use crate::projection::Projection;
    pub use crate::resource::{MachinePhysicalSpec, ExecutionHint, ResourceClass, ThreadPoolSpec};
    pub use crate::session::{
        SessionType, SessionOp, SessionState, SessionProtocol, SessionError, is_dual,
        GlobalType, GlobalOp, LocalType, LocalOp, Role, project, is_consistent,
    };
    pub use crate::static_exec::{
        StaticExecError,
        StraightMachine, StraightLink, StraightId, StraightSplit, StraightClone, StraightMerge,
        Chain, Diamond, Composite, StaticChain, FlowThrough, run_parallel,
    };
    pub use crate::time::{TimeTick, Clock, RealClock, ReplayClock};
    pub use crate::topology::{
        Topology, StaticTopology, TopologyMutation, TopologyOp, TopologyDelta, AppliedOp,
        TopologyError,
    };
    pub use crate::analysis::{
        TopologyWarning, FeedbackLoop, SinglePointOfFailure, TopologyReport,
    };

    /// The port declaration macro for multi-port Machines.
    pub use crate::declare_ports;
}
