/// PortSet — type-level port declarations for axiom Machines.
///
/// # The problem this solves
///
/// Mathematically (foundations.md §2), a Machine's input/output are
/// *interface sets* Γ = {p₁, p₂, …} — finite sets of ports. Each port
/// p = (T, d, f) carries a type T, direction d, and flow kind f.
///
/// The `Machine` trait therefore requires:
/// - `type Input: HasPortInfo`  — an enum with one variant per input port
/// - `type Output: HasPortInfo` — an enum with one variant per output port
/// - `type Ports: PortSet`      — connects the enums to a `PortSchema`
///
/// `port_schema()` is auto-derived from `Self::Ports::port_schema()`,
/// eliminating the gap between type-space and value-space port declarations.
///
/// # Usage with `declare_ports!`
///
/// ```ignore
/// use axiom::prelude_all::*;
///
/// declare_ports! {
///     pub struct MyPorts {
///         input type MyInput {
///             data_in  [Data]    => f64,
///             ctrl_in  [Control] => ShutdownCmd,
///         }
///         output type MyOutput {
///             result [Data]    => OutputValue,
///             status [Observe] => StatusReport,
///         }
///     }
/// }
///
/// struct MyMachine;
/// impl Machine for MyMachine {
///     type State  = MyState;
///     type Input  = MyInput;
///     type Output = MyOutput;
///     type Ports  = MyPorts;          // ← port_schema() auto-derived
///     // ...
/// }
/// ```
///
/// # Single-port convenience
///
/// For machines with exactly one input and/or one output port,
/// use the `In<T>` / `Out<T>` wrappers and `SinglePort<T>` PortSet:
///
/// ```ignore
/// impl Machine for Doubler {
///     type State  = ();
///     type Input  = In<i32>;
///     type Output = Out<i32>;
///     type Ports  = SinglePorts<i32>;
///     // ...
/// }
/// ```

use crate::flow::FlowKind;
use crate::port::PortSchema;
use core::any::{Any, TypeId};

// ── PortSet trait ─────────────────────────────────────────────────────────────

/// A set of input and output ports for a Machine.
///
/// Implemented by the struct generated by `declare_ports!` or by the
/// built-in `SinglePorts<T>` / `EmptyPorts` convenience types.
pub trait PortSet: Send + Sync + 'static {
    /// The input-port enum: one variant per declared input port.
    type Input: HasPortInfo;
    /// The output-port enum: one variant per declared output port.
    type Output: HasPortInfo;

    /// Build a `PortSchema` from all declared ports.
    fn port_schema() -> PortSchema;
}

// ── HasPortInfo trait ─────────────────────────────────────────────────────────

/// Runtime port introspection on an enum variant.
///
/// Implemented by the input/output enums generated by `declare_ports!`,
/// or by the built-in `In<T>` / `Out<T>` wrappers.
///
/// # Why `Clone`
/// `ProcessOutput<O>: Clone` requires `O: Clone`. Since every `Machine::Output`
/// must implement `HasPortInfo`, the trait bound includes `Clone`.
pub trait HasPortInfo: Send + Sized + Clone + 'static {
    /// The port name this value arrived on / will be sent on.
    fn port_name(&self) -> &'static str;
    /// The flow kind of this port.
    fn flow_kind(&self) -> FlowKind;
    /// The TypeId of the payload.
    fn payload_type_id(&self) -> TypeId;
    /// The type name string of the payload.
    fn payload_type_name(&self) -> &'static str;
    /// Reconstruct an input value from a port name + type-erased payload.
    /// Returns `None` if the port name is unknown or the type doesn't match.
    fn from_port_name(name: &str, payload: Box<dyn Any + Send>) -> Option<Self>
    where
        Self: Sized;
    /// Erase the payload type for transport over channels.
    fn into_any(self) -> Box<dyn Any + Send>;
}

// ── declare_ports! macro ──────────────────────────────────────────────────────

/// Generate Input/Output port enums and PortSchema derivation.
///
/// # Syntax
///
/// ```ignore
/// declare_ports! {
///     pub struct PortSetName {
///         input type InputEnumName {
///             port_a [Data] => TypeA,
///             port_b [Control] => TypeB,
///         }
///         output type OutputEnumName {
///             port_c [Data] => TypeC,
///             port_d [Observe] => TypeD,
///         }
///     }
/// }
/// ```
///
/// Generates:
/// - `InputEnumName` enum with variant `port_a(TypeA)`, `port_b(TypeB)`, etc.
/// - `OutputEnumName` enum with variant `port_c(TypeC)`, `port_d(TypeD)`, etc.
/// - `impl PortSet for PortSetName` with associated types and `port_schema()`.
/// - `impl HasPortInfo` for both enums.
#[macro_export]
macro_rules! declare_ports {
    // ── Public struct with explicit enum names ──────────────
    (
        $( #[$meta:meta] )*
        pub struct $name:ident {
            input type $input_enum:ident {
                $(
                    $( #[$in_meta:meta] )*
                    $in_name:ident [ $in_flow:ident ] => $in_ty:ty
                ),* $(,)?
            }
            output type $output_enum:ident {
                $(
                    $( #[$out_meta:meta] )*
                    $out_name:ident [ $out_flow:ident ] => $out_ty:ty
                ),* $(,)?
            }
        }
    ) => {
        $( #[$meta] )*
        pub struct $name;

        // ── Input enum ──────────────────────────────────
        $( #[$meta] )*
        #[derive(Debug, Clone, PartialEq)]
        #[allow(non_camel_case_types)]
        pub enum $input_enum {
            $(
                $( #[$in_meta] )*
                $in_name($in_ty),
            )*
        }

        // ── Output enum ─────────────────────────────────
        $( #[$meta] )*
        #[derive(Debug, Clone, PartialEq)]
        #[allow(non_camel_case_types)]
        pub enum $output_enum {
            $(
                $( #[$out_meta] )*
                $out_name($out_ty),
            )*
        }

        // ── PortSet impl ────────────────────────────────
        impl $crate::portset::PortSet for $name {
            type Input = $input_enum;
            type Output = $output_enum;

            fn port_schema() -> $crate::port::PortSchema {
                let mut schema = $crate::port::PortSchema::new();
                $(
                    schema = schema.with($crate::port::PortDecl::new::<$in_ty>(
                        stringify!($in_name),
                        $crate::port::PortDir::In,
                        $crate::flow::FlowKind::$in_flow,
                    ));
                )*
                $(
                    schema = schema.with($crate::port::PortDecl::new::<$out_ty>(
                        stringify!($out_name),
                        $crate::port::PortDir::Out,
                        $crate::flow::FlowKind::$out_flow,
                    ));
                )*
                schema
            }
        }

        // ── HasPortInfo for Input ───────────────────────
        impl $crate::portset::HasPortInfo for $input_enum {
            fn port_name(&self) -> &'static str {
                match self {
                    $( $input_enum::$in_name(_) => stringify!($in_name), )*
                }
            }

            fn flow_kind(&self) -> $crate::flow::FlowKind {
                match self {
                    $( $input_enum::$in_name(_) => $crate::flow::FlowKind::$in_flow, )*
                }
            }

            fn payload_type_id(&self) -> ::core::any::TypeId {
                match self {
                    $( $input_enum::$in_name(_) => ::core::any::TypeId::of::<$in_ty>(), )*
                }
            }

            fn payload_type_name(&self) -> &'static str {
                match self {
                    $( $input_enum::$in_name(_) => ::core::any::type_name::<$in_ty>(), )*
                }
            }

            fn from_port_name(name: &str, payload: Box<dyn ::core::any::Any + Send>) -> Option<Self> {
                match name {
                    $( stringify!($in_name) => {
                        let val: Box<$in_ty> = payload.downcast().ok()?;
                        Some($input_enum::$in_name(*val))
                    }, )*
                    _ => None,
                }
            }

            fn into_any(self) -> Box<dyn ::core::any::Any + Send> {
                match self {
                    $( $input_enum::$in_name(v) => Box::new(v), )*
                }
            }
        }

        // ── HasPortInfo for Output ──────────────────────
        impl $crate::portset::HasPortInfo for $output_enum {
            fn port_name(&self) -> &'static str {
                match self {
                    $( $output_enum::$out_name(_) => stringify!($out_name), )*
                }
            }

            fn flow_kind(&self) -> $crate::flow::FlowKind {
                match self {
                    $( $output_enum::$out_name(_) => $crate::flow::FlowKind::$out_flow, )*
                }
            }

            fn payload_type_id(&self) -> ::core::any::TypeId {
                match self {
                    $( $output_enum::$out_name(_) => ::core::any::TypeId::of::<$out_ty>(), )*
                }
            }

            fn payload_type_name(&self) -> &'static str {
                match self {
                    $( $output_enum::$out_name(_) => ::core::any::type_name::<$out_ty>(), )*
                }
            }

            fn from_port_name(name: &str, payload: Box<dyn ::core::any::Any + Send>) -> Option<Self> {
                match name {
                    $( stringify!($out_name) => {
                        let val: Box<$out_ty> = payload.downcast().ok()?;
                        Some($output_enum::$out_name(*val))
                    }, )*
                    _ => None,
                }
            }

            fn into_any(self) -> Box<dyn ::core::any::Any + Send> {
                match self {
                    $( $output_enum::$out_name(v) => Box::new(v), )*
                }
            }
        }
    };
}

// ════════════════════════════════════════════════════════════════════════════
// Single-port convenience types
// ════════════════════════════════════════════════════════════════════════════

/// Single input port wrapper. Use when a Machine has exactly one input port.
///
/// ```ignore
/// impl Machine for Doubler {
///     type Input = In<i32>;
///     type Output = Out<i32>;
///     type Ports = SinglePorts<i32>;
///     // ...
/// }
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct In<T>(pub T);

impl<T: Send + Clone + 'static> HasPortInfo for In<T> {
    fn port_name(&self) -> &'static str { "input" }
    fn flow_kind(&self) -> FlowKind { FlowKind::Data }
    fn payload_type_id(&self) -> TypeId { TypeId::of::<T>() }
    fn payload_type_name(&self) -> &'static str { core::any::type_name::<T>() }
    fn from_port_name(name: &str, payload: Box<dyn Any + Send>) -> Option<Self> {
        match name {
            "input" => payload.downcast::<T>().ok().map(|v| In(*v)),
            _ => None,
        }
    }
    fn into_any(self) -> Box<dyn Any + Send> { Box::new(self.0) }
}

/// Single output port wrapper. Use when a Machine has exactly one output port.
#[derive(Debug, Clone, PartialEq)]
pub struct Out<T>(pub T);

impl<T: Send + Sync + Clone + 'static> HasPortInfo for Out<T> {
    fn port_name(&self) -> &'static str { "output" }
    fn flow_kind(&self) -> FlowKind { FlowKind::Data }
    fn payload_type_id(&self) -> TypeId { TypeId::of::<T>() }
    fn payload_type_name(&self) -> &'static str { core::any::type_name::<T>() }
    fn from_port_name(name: &str, payload: Box<dyn Any + Send>) -> Option<Self> {
        match name {
            "output" => payload.downcast::<T>().ok().map(|v| Out(*v)),
            _ => None,
        }
    }
    fn into_any(self) -> Box<dyn Any + Send> { Box::new(self.0) }
}

/// PortSet for a single-input, single-output Machine (both Data flow).
///
/// Use with `In<T>` and `Out<T>`.
pub struct SinglePorts<T>(core::marker::PhantomData<T>);

impl<T: Send + Sync + Clone + 'static> PortSet for SinglePorts<T> {
    type Input = In<T>;
    type Output = Out<T>;

    fn port_schema() -> PortSchema {
        PortSchema::new()
            .with(crate::port::PortDecl::input::<T>("input"))
            .with(crate::port::PortDecl::output::<T>("output"))
    }
}

// ════════════════════════════════════════════════════════════════════════════
// Empty port sets (for Machines with no input or no output)
// ════════════════════════════════════════════════════════════════════════════

/// Zero-variant output enum: a Machine with no output ports.
/// `ProcessOutput::Yield` can never be constructed for this type.
#[derive(Debug, Clone, PartialEq)]
pub enum NoOutput {}

impl HasPortInfo for NoOutput {
    fn port_name(&self) -> &'static str { match *self {} }
    fn flow_kind(&self) -> FlowKind { match *self {} }
    fn payload_type_id(&self) -> TypeId { match *self {} }
    fn payload_type_name(&self) -> &'static str { match *self {} }
    fn from_port_name(_name: &str, _payload: Box<dyn Any + Send>) -> Option<Self> { None }
    fn into_any(self) -> Box<dyn Any + Send> { match self {} }
}

/// Zero-variant input enum: a Machine with no input ports (pure source).
#[derive(Debug, Clone, PartialEq)]
pub enum NoInput {}

impl HasPortInfo for NoInput {
    fn port_name(&self) -> &'static str { match *self {} }
    fn flow_kind(&self) -> FlowKind { match *self {} }
    fn payload_type_id(&self) -> TypeId { match *self {} }
    fn payload_type_name(&self) -> &'static str { match *self {} }
    fn from_port_name(_name: &str, _payload: Box<dyn Any + Send>) -> Option<Self> { None }
    fn into_any(self) -> Box<dyn Any + Send> { match self {} }
}
