/// PortSet — type-level port declarations for axiom Machines.
///
/// # The problem this solves
///
/// Mathematically (foundations.md §2), a Machine's input/output are
/// *interface sets* Γ = {p₁, p₂, …} — finite sets of ports. Each port
/// p = (T, d, f) carries a type T, direction d, and flow kind f.
///
/// The `Machine` trait therefore requires:
/// - `type Input: HasPortInfo`  — an enum with one variant per input port
/// - `type Output: HasPortInfo` — an enum with one variant per output port
/// - `type Ports: PortSet`      — connects the enums to a `PortSchema`
///
/// `port_schema()` is auto-derived from `Self::Ports::port_schema()`,
/// eliminating the gap between type-space and value-space port declarations.
///
/// # Usage with `declare_ports!`
///
/// ```ignore
/// use axiom::prelude_all::*;
///
/// declare_ports! {
///     // Derives are forwarded to the generated enums; add them as needed.
///     // axiom does NOT force `Clone` — a non-Clone payload can be a port type.
///     #[derive(Debug, Clone, PartialEq)]
///     pub struct MyPorts {
///         input type MyInput {
///             data_in  [Data]    => f64,
///             ctrl_in  [Control] => ShutdownCmd,
///         }
///         output type MyOutput {
///             result [Data]    => OutputValue,
///             status [Observe] => StatusReport,
///         }
///     }
/// }
///
/// struct MyMachine;
/// impl Machine for MyMachine {
///     type State  = MyState;
///     type Input  = MyInput;
///     type Output = MyOutput;
///     type Ports  = MyPorts;          // ← port_schema() auto-derived
///     // ...
/// }
/// ```
///
/// # Single-port convenience
///
/// For machines with exactly one input and/or one output port,
/// use the `In<T>` / `Out<T>` wrappers and `SinglePort<T>` PortSet:
///
/// ```ignore
/// impl Machine for Doubler {
///     type State  = ();
///     type Input  = In<i32>;
///     type Output = Out<i32>;
///     type Ports  = SinglePorts<i32>;
///     // ...
/// }
/// ```

#[cfg(not(feature = "std"))]
use crate::compat::prelude::*;
use crate::flow::FlowKind;
use crate::port::PortSchema;
use core::any::{Any, TypeId};

// ── PortSet trait ─────────────────────────────────────────────────────────────

/// A set of input and output ports for a Machine.
///
/// Implemented by the struct generated by `declare_ports!` or by the
/// built-in `SinglePorts<T>` / `EmptyPorts` convenience types.
pub trait PortSet: Send + Sync + 'static {
    /// The input-port enum: one variant per declared input port.
    type Input: HasPortInfo;
    /// The output-port enum: one variant per declared output port.
    type Output: HasPortInfo;

    /// Build a `PortSchema` from all declared ports.
    fn port_schema() -> PortSchema;
}

// ── HasPortInfo trait ─────────────────────────────────────────────────────────

/// Runtime port introspection on an enum variant.
///
/// Implemented by the input/output enums generated by `declare_ports!`,
/// or by the built-in `In<T>` / `Out<T>` wrappers.
///
/// # Deliberately no `Clone` bound
/// Port values cross the port boundary by **move**, not by clone — Rust's
/// default semantics. `HasPortInfo` therefore does not require `Clone`: a
/// payload that is not `Clone` (e.g. an owned buffer, a handle, a `Box<dyn
/// Fn>`) can still be transported type-erased via `into_any`/`from_port_name`.
/// Snapshotting/auditing needs belong to explicit contracts
/// (`Machine::checkpoint`/`restore`), not to a blanket clone obligation on
/// every payload.
pub trait HasPortInfo: Send + Sized + 'static {
    /// The port name this value arrived on / will be sent on.
    fn port_name(&self) -> &'static str;
    /// The flow kind of this port.
    fn flow_kind(&self) -> FlowKind;
    /// The TypeId of the payload.
    fn payload_type_id(&self) -> TypeId;
    /// The type name string of the payload.
    fn payload_type_name(&self) -> &'static str;
    /// Reconstruct an input value from a port name + type-erased payload.
    /// Returns `None` if the port name is unknown or the type doesn't match.
    fn from_port_name(name: &str, payload: Box<dyn Any + Send>) -> Option<Self>
    where
        Self: Sized;
    /// Erase the payload type for transport over channels.
    fn into_any(self) -> Box<dyn Any + Send>;
}

/// 从端口 enum 提取裸值（不装箱）——单输出机器的级间免装箱协议
/// （runtime 类型化值槽的配合契约：级间裸值直传，零分配）。
///
/// [`declare_ports!`] 为单输出端口 enum 生成此实现（`Raw` = 唯一负载类型）。
/// **仅单输出机器（`FusedInline`）使用**——多输出机器不进入融合链。
pub trait Unpack: Sized {
    /// 裸值类型（单输出端口 enum 的负载，需可跨线程传递）。
    type Raw: 'static + Send;
    /// 解包：`Self` 是单输出端口 enum，返回其负载（move，零分配）。
    fn unpack(self) -> Self::Raw;
}

/// 从裸值构造端口 enum（不装箱）——[`Unpack`] 的对偶。
///
/// [`declare_ports!`] 为单输入端口 enum 生成此实现。级间免装箱协议用
/// `Pack::pack(裸值)` 构造输入 variant，避免 `from_port_name` 的 `Box`
/// 解包消费分配。
pub trait Pack: Sized {
    /// 裸值类型（单输入端口 enum 的负载，需可跨线程传递）。
    type Raw: 'static + Send;
    /// 打包：从裸值构造 `Self`（move，零分配）。
    fn pack(raw: Self::Raw) -> Self;
}

/// 单输出检测 + Unpack 生成（宏辅助）：恰好一个输出端口时生成
/// [`Unpack`]；多输出/空输出不生成（不进融合链）。
#[doc(hidden)]
#[macro_export]
macro_rules! __declare_unpack {
    // 单输出：生成 Unpack（裸值 = 唯一负载类型）。
    ($output_enum:ident, $out_name:ident [ $out_flow:ident ] => $out_ty:ty) => {
        impl $crate::portset::Unpack for $output_enum {
            type Raw = $out_ty;
            fn unpack(self) -> Self::Raw {
                match self {
                    $output_enum::$out_name(v) => v,
                }
            }
        }
    };
    // 多输出：不生成（多输出机器非 FusedInline，不进融合链）。
    ($output_enum:ident, $($out_name:ident [ $out_flow:ident ] => $out_ty:ty),+ $(,)?) => {};
    // 空输出：不生成。
    ($output_enum:ident $(,)?) => {};
}

/// 单输入检测 + Pack 生成（宏辅助）：恰好一个输入端口时生成
/// [`Pack`]；多输入/空输入不生成（级间协议仅服务单输入机器）。
#[doc(hidden)]
#[macro_export]
macro_rules! __declare_pack {
    // 单输入：生成 Pack（裸值 = 唯一负载类型）。
    ($input_enum:ident, $in_name:ident [ $in_flow:ident ] => $in_ty:ty) => {
        impl $crate::portset::Pack for $input_enum {
            type Raw = $in_ty;
            fn pack(raw: Self::Raw) -> Self {
                $input_enum::$in_name(raw)
            }
        }
    };
    // 多输入：不生成。
    ($input_enum:ident, $($in_name:ident [ $in_flow:ident ] => $in_ty:ty),+ $(,)?) => {};
    // 空输入：不生成。
    ($input_enum:ident $(,)?) => {};
}

// ── declare_ports! macro ──────────────────────────────────────────────────────

/// Generate Input/Output port enums and PortSchema derivation.
///
/// # Syntax
///
/// ```ignore
/// declare_ports! {
///     pub struct PortSetName {
///         input type InputEnumName {
///             port_a [Data] => TypeA,
///             port_b [Control] => TypeB,
///         }
///         output type OutputEnumName {
///             port_c [Data] => TypeC,
///             port_d [Observe] => TypeD,
///         }
///     }
/// }
/// ```
///
/// # 端口负载类型的可见性契约
///
/// 端口负载类型（`TypeA`/`TypeB`/`TypeC`/`TypeD` 等）**必须是 `pub`**：
/// [`Unpack`]/[`Pack`]（单输入单输出机器的级间免装箱协议）公开
/// `type Raw`，私有负载类型会导致 `E0446`（私有类型泄漏到公开接口）。
/// 端口是跨机器链接的类型契约（`LinkSpec` 校验类型匹配），公开负载类型
/// 是 axiom 的接口要求。
///
/// Generates:
/// - `InputEnumName` enum with variant `port_a(TypeA)`, `port_b(TypeB)`, etc.
/// - `OutputEnumName` enum with variant `port_c(TypeC)`, `port_d(TypeD)`, etc.
/// - `impl PortSet for PortSetName` with associated types and `port_schema()`.
/// - `impl HasPortInfo` for both enums.
/// # Compile-fail guarantees
///
/// Wrong usage is rejected at compile time — the macro generates enums from
/// the declared ports, so malformed flows or duplicate port names surface as
/// compile errors rather than runtime surprises (compile-time macro diagnostics):
///
/// ```compile_fail
/// // 流类型拼写错误：`Dta` 不是 `FlowKind` 变体 → 编译失败
/// axiom::declare_ports! {
///     pub struct BadFlowPorts {
///         input type BadFlowInput {
///             x[Dta] => i32,
///         }
///         output type BadFlowOutput {
///             y[Data] => i32,
///         }
///     }
/// }
/// ```
///
/// ```compile_fail
/// // 重复端口名：生成重复枚举变体 → 编译失败
/// axiom::declare_ports! {
///     pub struct DupPorts {
///         input type DupInput {
///             x[Data] => i32,
///             x[Data] => i32,
///         }
///         output type DupOutput {
///             y[Data] => i32,
///         }
///     }
/// }
/// ```
#[macro_export]
macro_rules! declare_ports {
    // ── Public struct with explicit enum names ──────────────
    (
        $( #[$meta:meta] )*
        pub struct $name:ident {
            input type $input_enum:ident {
                $(
                    $( #[$in_meta:meta] )*
                    $in_name:ident [ $in_flow:ident ] => $in_ty:ty
                ),* $(,)?
            }
            output type $output_enum:ident {
                $(
                    $( #[$out_meta:meta] )*
                    $out_name:ident [ $out_flow:ident ] => $out_ty:ty
                ),* $(,)?
            }
        }
    ) => {
        $( #[$meta] )*
        pub struct $name;

        // ── Input enum ──────────────────────────────────
        // Derives come from the caller via `$( #[$meta] )*` (typically a
        // `#[derive(...)]` on the struct, forwarded to both enums). axiom does
        // NOT force Clone/PartialEq here — a non-Clone payload can be used as
        // a port type; add derives only if your payload supports them.
        $( #[$meta] )*
        #[allow(non_camel_case_types)]
        pub enum $input_enum {
            $(
                $( #[$in_meta] )*
                $in_name($in_ty),
            )*
        }

        // ── Output enum ─────────────────────────────────
        // Same derive policy as the input enum (see above).
        $( #[$meta] )*
        #[allow(non_camel_case_types)]
        pub enum $output_enum {
            $(
                $( #[$out_meta] )*
                $out_name($out_ty),
            )*
        }

        // ── PortSet impl ────────────────────────────────
        impl $crate::portset::PortSet for $name {
            type Input = $input_enum;
            type Output = $output_enum;

            fn port_schema() -> $crate::port::PortSchema {
                let mut schema = $crate::port::PortSchema::new();
                $(
                    schema = schema.with($crate::port::PortDecl::new::<$in_ty>(
                        stringify!($in_name),
                        $crate::port::PortDir::In,
                        $crate::flow::FlowKind::$in_flow,
                    ));
                )*
                $(
                    schema = schema.with($crate::port::PortDecl::new::<$out_ty>(
                        stringify!($out_name),
                        $crate::port::PortDir::Out,
                        $crate::flow::FlowKind::$out_flow,
                    ));
                )*
                schema
            }
        }

        // ── HasPortInfo for Input ───────────────────────
        impl $crate::portset::HasPortInfo for $input_enum {
            fn port_name(&self) -> &'static str {
                match *self {
                    $( $input_enum::$in_name(..) => stringify!($in_name), )*
                }
            }

            fn flow_kind(&self) -> $crate::flow::FlowKind {
                match *self {
                    $( $input_enum::$in_name(..) => $crate::flow::FlowKind::$in_flow, )*
                }
            }

            fn payload_type_id(&self) -> ::core::any::TypeId {
                match *self {
                    $( $input_enum::$in_name(..) => ::core::any::TypeId::of::<$in_ty>(), )*
                }
            }

            fn payload_type_name(&self) -> &'static str {
                match *self {
                    $( $input_enum::$in_name(..) => ::core::any::type_name::<$in_ty>(), )*
                }
            }

            fn from_port_name(name: &str, payload: Box<dyn ::core::any::Any + Send>) -> Option<Self> {
                match name {
                    $( stringify!($in_name) => {
                        let val: Box<$in_ty> = payload.downcast().ok()?;
                        Some($input_enum::$in_name(*val))
                    }, )*
                    _ => None,
                }
            }

            fn into_any(self) -> Box<dyn ::core::any::Any + Send> {
                match self {
                    $( $input_enum::$in_name(v) => Box::new(v), )*
                }
            }
        }

        // ── Pack for Input（级间免装箱协议：裸值 → variant，零分配）──────
        $crate::__declare_pack!($input_enum, $( $in_name [ $in_flow ] => $in_ty ),*);

        // ── HasPortInfo for Output ──────────────────────
        impl $crate::portset::HasPortInfo for $output_enum {
            fn port_name(&self) -> &'static str {
                match *self {
                    $( $output_enum::$out_name(..) => stringify!($out_name), )*
                }
            }

            fn flow_kind(&self) -> $crate::flow::FlowKind {
                match *self {
                    $( $output_enum::$out_name(..) => $crate::flow::FlowKind::$out_flow, )*
                }
            }

            fn payload_type_id(&self) -> ::core::any::TypeId {
                match *self {
                    $( $output_enum::$out_name(..) => ::core::any::TypeId::of::<$out_ty>(), )*
                }
            }

            fn payload_type_name(&self) -> &'static str {
                match *self {
                    $( $output_enum::$out_name(..) => ::core::any::type_name::<$out_ty>(), )*
                }
            }

            fn from_port_name(name: &str, payload: Box<dyn ::core::any::Any + Send>) -> Option<Self> {
                match name {
                    $( stringify!($out_name) => {
                        let val: Box<$out_ty> = payload.downcast().ok()?;
                        Some($output_enum::$out_name(*val))
                    }, )*
                    _ => None,
                }
            }

            fn into_any(self) -> Box<dyn ::core::any::Any + Send> {
                match self {
                    $( $output_enum::$out_name(v) => Box::new(v), )*
                }
            }
        }

        // ── Unpack for Output（级间免装箱协议：variant → 裸值，零分配）────
        $crate::__declare_unpack!($output_enum, $( $out_name [ $out_flow ] => $out_ty ),*);
    };
}

// ════════════════════════════════════════════════════════════════════════════
// Single-port convenience types
// ════════════════════════════════════════════════════════════════════════════

/// Single input port wrapper. Use when a Machine has exactly one input port.
///
/// ```ignore
/// impl Machine for Doubler {
///     type Input = In<i32>;
///     type Output = Out<i32>;
///     type Ports = SinglePorts<i32>;
///     // ...
/// }
/// ```
///
/// `Debug`/`Clone`/`PartialEq` are **conditional** on `T` (hand-written impls,
/// not derives) — axiom does not force `T: Clone`, matching the Clone-free
/// `HasPortInfo` contract.
pub struct In<T>(pub T);

impl<T: core::fmt::Debug> core::fmt::Debug for In<T> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_tuple("In").field(&self.0).finish()
    }
}

impl<T: Clone> Clone for In<T> {
    fn clone(&self) -> Self {
        In(self.0.clone())
    }
}

impl<T: PartialEq> PartialEq for In<T> {
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}

impl<T: Send + 'static> HasPortInfo for In<T> {
    fn port_name(&self) -> &'static str { "input" }
    fn flow_kind(&self) -> FlowKind { FlowKind::Data }
    fn payload_type_id(&self) -> TypeId { TypeId::of::<T>() }
    fn payload_type_name(&self) -> &'static str { core::any::type_name::<T>() }
    fn from_port_name(name: &str, payload: Box<dyn Any + Send>) -> Option<Self> {
        match name {
            "input" => payload.downcast::<T>().ok().map(|v| In(*v)),
            _ => None,
        }
    }
    fn into_any(self) -> Box<dyn Any + Send> { Box::new(self.0) }
}

impl<T: Send + 'static> Pack for In<T> {
    type Raw = T;
    fn pack(raw: T) -> Self {
        In(raw)
    }
}

/// Single output port wrapper. Use when a Machine has exactly one output port.
///
/// `Debug`/`Clone`/`PartialEq` are **conditional** on `T` — see [`In`].
pub struct Out<T>(pub T);

impl<T: core::fmt::Debug> core::fmt::Debug for Out<T> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_tuple("Out").field(&self.0).finish()
    }
}

impl<T: Clone> Clone for Out<T> {
    fn clone(&self) -> Self {
        Out(self.0.clone())
    }
}

impl<T: PartialEq> PartialEq for Out<T> {
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}

impl<T: Send + Sync + 'static> HasPortInfo for Out<T> {
    fn port_name(&self) -> &'static str { "output" }
    fn flow_kind(&self) -> FlowKind { FlowKind::Data }
    fn payload_type_id(&self) -> TypeId { TypeId::of::<T>() }
    fn payload_type_name(&self) -> &'static str { core::any::type_name::<T>() }
    fn from_port_name(name: &str, payload: Box<dyn Any + Send>) -> Option<Self> {
        match name {
            "output" => payload.downcast::<T>().ok().map(|v| Out(*v)),
            _ => None,
        }
    }
    fn into_any(self) -> Box<dyn Any + Send> { Box::new(self.0) }
}

impl<T: Send + 'static> Unpack for Out<T> {
    type Raw = T;
    fn unpack(self) -> T {
        self.0
    }
}

/// PortSet for a single-input, single-output Machine (both Data flow).
///
/// Use with `In<T>` and `Out<T>`.
pub struct SinglePorts<T>(core::marker::PhantomData<T>);

impl<T: Send + Sync + 'static> PortSet for SinglePorts<T> {
    type Input = In<T>;
    type Output = Out<T>;

    fn port_schema() -> PortSchema {
        PortSchema::new()
            .with(crate::port::PortDecl::input::<T>("input"))
            .with(crate::port::PortDecl::output::<T>("output"))
    }
}

// ════════════════════════════════════════════════════════════════════════════
// Empty port sets (for Machines with no input or no output)
// ════════════════════════════════════════════════════════════════════════════

/// Zero-variant output enum: a Machine with no output ports.
/// `ProcessOutput::Yield` can never be constructed for this type.
#[derive(Debug, Clone, PartialEq)]
pub enum NoOutput {}

impl HasPortInfo for NoOutput {
    fn port_name(&self) -> &'static str { match *self {} }
    fn flow_kind(&self) -> FlowKind { match *self {} }
    fn payload_type_id(&self) -> TypeId { match *self {} }
    fn payload_type_name(&self) -> &'static str { match *self {} }
    fn from_port_name(_name: &str, _payload: Box<dyn Any + Send>) -> Option<Self> { None }
    fn into_any(self) -> Box<dyn Any + Send> { match self {} }
}

/// Zero-variant input enum: a Machine with no input ports (pure source).
#[derive(Debug, Clone, PartialEq)]
pub enum NoInput {}

impl HasPortInfo for NoInput {
    fn port_name(&self) -> &'static str { match *self {} }
    fn flow_kind(&self) -> FlowKind { match *self {} }
    fn payload_type_id(&self) -> TypeId { match *self {} }
    fn payload_type_name(&self) -> &'static str { match *self {} }
    fn from_port_name(_name: &str, _payload: Box<dyn Any + Send>) -> Option<Self> { None }
    fn into_any(self) -> Box<dyn Any + Send> { match self {} }
}
